name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Backend Dependencies
      run: npm ci
    
    - name: Build Backend
      run: npm run build

    - name: Commit built backend
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add dist
        git commit -m "Build backend for deployment [skip ci]" || echo "No changes to commit"
        git push
    
    - name: Build frontend
      run: |
        cd cufc-frontend
        npm run build
      env:
        VITE_CUSTOM_VAR: ${{ vars.VITE_CUSTOM_VAR }}

    - name: Commit built frontend
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add cufc-frontend/dist
        git commit -m "Build frontend for deployment [skip ci]" || echo "No changes to commit"
        git push
